# YOUR NAME OR TITLE OF YOUR SITE
name: reske

# YOUR BRAND/PERSONAL TAGLINE
tagline: Hi? This is the part where I'm supposed to show off with some cool ass bio although I personally don't care, either find a way to me or simply go away, but other than that. I do some cool magic stuff though.

# YOUR/BRAND IMAGE URL
Image_URL: https://i.imgur.com/teJPSqJ.jpg

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://i.imgur.com/uqtnP78.jpg

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # FACEBOOK
  - Name: Facebook
    URL: 
    Username: harsh98trivedi
    Color: '#3b5998'
    Icon-Class: fab fa-facebook

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: reskehd
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: reskehd
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

    # CLUBHOUSE
  - Name: Clubhouse
    URL: 
    Username: '@harsh98trivedi'
    Color: '#f1c40f'
    Icon-Class: fas fa-hand-paper -mt-0.5
    
    # LINKEDIN
  - Name: LinkedIn
    URL: 
    Username: harsh98trivedi
    Color: '#2867B2'
    Icon-Class: fab fa-linkedin-in

    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/channel
    Username: UC9FJ6GVQr4sbuWubrGEr1ow
    Color: '#ff0000'
    Icon-Class: fab fa-youtube

    # GITHUB
  - Name: GitHub
    URL: 
    Username: harsh98trivedi
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # EMAIL
  - Name: Email
    URL: 
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'

    # TWITCH
  - Name: Twitch
    URL: 
    Username: harsh98trivedi
    Icon-Class: fab fa-twitch
    Color: '#9147fe'
    Text_Color: '#ffffff'

    # VIMEO
  - Name: Vimeo
    URL: 
    Username: harshtrivedi
    Icon-Class: fab fa-vimeo-v
    Color: '#1ab7ea'
    Text_Color: '#ffffff'

    # MESSENGER
  - Name: Messenger
    URL: 
    Username: theharshtrivedi
    Color: '#006AFF'
    Icon-Class: fab fa-facebook-messenger

    # REDDIT
  - Name: Reddit
    URL: 
    Username: harshtrivedi
    Color: '#FF4500'
    Icon-Class: fab fa-reddit-alien

  #   # WHATSAPP
  # - Name: WhatsApp
  #   URL: https://wa.me
  #   Username: '+1123456789'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp

    # TELEGRAM
  - Name: Telegram
    URL: 
    Username: theharshtrivedi
    Color: '#0088cc'
    Icon-Class: fab fa-telegram-plane

    # SNAPCHAT
  - Name: Snapchat
    URL: 
    Username: 'harsh98trivedi'
    Color: '#FFFC00'
    Text_Color: '#000000'
    Icon-Class: fab fa-snapchat-ghost

    # STEAM
  - Name: Steam
    URL: https://steamcommunity.com/id
    Username: 'reske69'
    Color: '#66c0f4'
    Text_Color: '#000000'
    Icon-Class: fab fa-steam

  #   # DISCORD
  # - Name: Discord
  #   URL: 'https://discord.gg'
  #   Username: 
  #   Icon-Class: fab fa-discord
  #   Color: '#5865F2'
  #   Text_Color: '#ffffff'

    # PINTEREST
  - Name: Pinterest
    URL: 
    Username: 'harsh98trivedi'
    Color: '#E60023'
    Icon-Class: fab fa-pinterest

    # BEHANCE
  - Name: Behance
    URL: 
    Username: 
    Color: '#1769ff'
    Icon-Class: fab fa-behance

  #   # DRIBBBLE
  # - Name: Dribbble
  #   URL: https://dribbble.com
  #   Username: 
  #   Color: '#ea4c89'
  #   Icon-Class: fab fa-dribbble

    # DEVIANTART
  - Name: DeviantArt
    URL: 
    Username: harshtrivedi
    Icon-Class: fab fa-deviantart
    Color: '#05CC46'
    Text_Color: '#ffffff'

    # FIGMA
  - Name: Figma
    URL: 
    Username: '@harshtrivedi'
    Icon-Class: fab fa-figma
    Color: '#ff2865'
    Text_Color: '#ffffff'

    # SPOTIFY
  - Name: Spotify
    URL: http://open.spotify.com/user
    Username: sdr68yubhw4ctdprwdi9wsftd
    Color: '#1DB954'
    Icon-Class: fab fa-spotify

    # SOUNDCLOUD
  - Name: SoundCloud
    URL: 
    Username: harsh98trivedi
    Color: '#FE5000'
    Icon-Class: fab fa-soundcloud

  #    # TIKTOK
  # - Name: TikTok
  #   URL: https://www.tiktok.com
  #   Username: 
  #   Color: '#FE2C55'
  #   Icon-Class: fab fa-tiktok

    # MEDIUM
  - Name: Medium
    URL: 
    Username: '@harsh98trivedi'
    Icon-Class: fab fa-medium-m
    Color: '#00ab6c'
    Text_Color: '#ffffff'

    # DEV.TO
  - Name: Dev.to
    URL: 
    Username: 
    Icon-Class: fab fa-dev
    Color: '#ffffff'
    Text_Color: '#000000'

  #   # TUMBLR
  # - Name: Tumblr
  #   URL: https://www.tumblr.com
  #   Username: 
  #   Color: '#35465c'
  #   Icon-Class: fab fa-tumblr

  # BUY ME A COFFEE
  - Name: BuyMeACoffee
    URL: 
    Username: harshtrivedi
    Icon-Class: fas fa-mug-hot
    Color: '#FFDD00'
    Text_Color: '#000000'

    # CUSTOM LINK
  - Name: Blog
    URL: 
    Icon-Class: fas fa-link
    Color: '#ffb142'
    Text_Color: '#ffffff'

  - Name: Links
    URL: 
    Icon-Class: fas fa-link
    Color: '#d94869'
    Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: ''

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
